// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUbH7TDzMmfIkxLCiPH-G8glF_c0BNau4',
    appId: '1:653161404357:web:8a9883be502d3e2e2f5dac',
    messagingSenderId: '653161404357',
    projectId: 'realtime-location-servic-c1cff',
    authDomain: 'realtime-location-servic-c1cff.firebaseapp.com',
    storageBucket: 'realtime-location-servic-c1cff.appspot.com',
    measurementId: 'G-2RHTNQRC8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJKyBUtBasi5JEZR58lPOFx0Xx9aibQo',
    appId: '1:653161404357:android:39826d6bc4d3ea8a2f5dac',
    messagingSenderId: '653161404357',
    projectId: 'realtime-location-servic-c1cff',
    storageBucket: 'realtime-location-servic-c1cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrwzo28TPt65xzMhywVU7CK82Bw1ltsk',
    appId: '1:653161404357:ios:a27e8f4a664582822f5dac',
    messagingSenderId: '653161404357',
    projectId: 'realtime-location-servic-c1cff',
    storageBucket: 'realtime-location-servic-c1cff.appspot.com',
    iosClientId: '653161404357-4p9f1foilk7mssjuq2d0315b9fiduu2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrwzo28TPt65xzMhywVU7CK82Bw1ltsk',
    appId: '1:653161404357:ios:a27e8f4a664582822f5dac',
    messagingSenderId: '653161404357',
    projectId: 'realtime-location-servic-c1cff',
    storageBucket: 'realtime-location-servic-c1cff.appspot.com',
    iosClientId: '653161404357-4p9f1foilk7mssjuq2d0315b9fiduu2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeLocation',
  );
}
